### getAll
GET http://localhost:4000/api/agendas HTTP/1.1

### getById
GET http://localhost:4000/api/agendas/1 HTTP/1.1

### getInfo
GET http://localhost:4000/api/agendas/40/info HTTP/1.1

### getTopics
GET http://localhost:4000/api/agendas/46/topics HTTP/1.1

### create
POST http://localhost:4000/api/agendas HTTP/1.1
Content-Type: application/json

# {
#   "year":"2025-11-21T19:15:05.706Z",
#   "idArea":1
# }

{
    "id": "",
    "year": "2025-03-20T05:10:53.141Z",
    "idTypeOfMeeting": 1
}

### update
PATCH  http://localhost:4000/api/agendas/40 HTTP/1.1
Content-Type: application/json

{
    "id": "40",
    "year": 2038,
    "idTypeOfMeeting": "1",
    "topics": [
      {
        "id": "14",
        "name": "TEMAZO 14",
        "month": "2023-01-01T05:00:00.000Z",
        "idAgenda": "40"
      },
      {
        "id": "70",
        "name": "TEMAZO 15",
        "month": "2023-05-01T05:00:00.000Z",
        "idAgenda": "40"
      },
      {
        "id": "71",
        "name": "TEMAZO 16",
        "month": "2023-05-01T05:00:00.000Z",
        "idAgenda": "40"
      },
      {
        "id": "",
        "name": "Nuevo Tema 1",
        "month": "2023-12-01T05:00:00.000Z",
        "idAgenda": "40"
      },
      {
        "id": "",
        "name": "Nuevo Tema 2",
        "month": "2023-07-01T05:00:00.000Z",
        "idAgenda": "40"
      },
      {
        "id": "",
        "name": "Nuevo Tema 3",
        "month": "2023-02-01T05:00:00.000Z",
        "idAgenda": "40"
      },
      {
        "id": "",
        "name": "NUEVO TEMA 001",
        "month": "2023-10-01T05:00:00.000Z",
        "idAgenda": "40"
      },
      {
        "id": "",
        "name": "NUEVO TEMA 010",
        "month": "2023-10-01T05:00:00.000Z",
        "idAgenda": "40"
      },
      {
        "id": "",
        "name": "NUEVO TEMA 100",
        "month": "2023-10-01T05:00:00.000Z",
        "idAgenda": "40"
      }
    ]
}
