### getAll
GET http://localhost:4000/api/workers HTTP/1.1

### getById
GET http://localhost:4000/api/workers/1 HTTP/1.1

### getAreas
GET http://localhost:4000/api/workers/3/areas

### create
POST http://localhost:4000/api/workers HTTP/1.1
Content-Type: application/json

{
  "name":"Trabajador 3",
  "occupation":"Ocupacion 3",
  "email":"email3@email.com",
  "idAreas":[1]
}

### update
PATCH  http://localhost:4000/api/workers/2 HTTP/1.1
Content-Type: application/json

{
  "name":"Trabajador 2",
  "occupation":"Ocupacion 2",
  "email":"email2@email.com",
  "idAreas":[3]
}

### remove
PATCH http://localhost:4000/api/workers/remove/1
